package com.hotelgalicia.proyectohotelgalicia.modelos;

public enum Municipios {
    ABADIN("Abadín", Provincias.LUGO),
    ABEGONDO("Abegondo", Provincias.A_CORUNA),
    AGOLADA("Agolada", Provincias.PONTEVEDRA),
    ALFOZ("Alfoz", Provincias.LUGO),
    ALLARIZ("Allariz", Provincias.OURENSE),
    AMES("Ames", Provincias.A_CORUNA),
    AMOEOIRO("Amoeiro", Provincias.OURENSE),
    ANTAS_DE_ULLA("Antas de Ulla", Provincias.LUGO),
    ARANGA("Aranga", Provincias.A_CORUNA),
    ARBO("Arbo", Provincias.PONTEVEDRA),
    ARES("Ares", Provincias.A_CORUNA),
    A_ARNOIA("A Arnoia", Provincias.OURENSE),
    ARTEIXO("Arteixo", Provincias.A_CORUNA),
    ARZUA("Arzúa", Provincias.A_CORUNA),
    AVION("Avión", Provincias.OURENSE),
    BAIONA("Baiona", Provincias.PONTEVEDRA),
    BALEIRA("Baleira", Provincias.LUGO),
    BALTAR("Baltar", Provincias.OURENSE),
    BANDE("Bande", Provincias.OURENSE),
    A_BANA("A Baña", Provincias.A_CORUNA),
    BANOS_DE_MOLGAS("Baños de Molgas", Provincias.OURENSE),
    BARALLA("Baralla", Provincias.LUGO),
    BARBADAS("Barbadás", Provincias.OURENSE),
    O_BARCO_DE_VALDEORRAS("O Barco de Valdeorras", Provincias.OURENSE),
    BARREIROS("Barreiros", Provincias.LUGO),
    BARRO("Barro", Provincias.PONTEVEDRA),
    BEADE("Beade", Provincias.OURENSE),
    BEARIZ("Beariz", Provincias.OURENSE),
    BOBORAS("Boborás", Provincias.OURENSE),
    BOIMORTO("Boimorto", Provincias.A_CORUNA),
    BOIRO("Boiro", Provincias.A_CORUNA),
    A_BOLA("A Bola", Provincias.OURENSE),
    O_BOLO("O Bolo", Provincias.OURENSE),
    BOQUEIXON("Boqueixón", Provincias.A_CORUNA),
    BOVEDA("Bóveda", Provincias.LUGO),
    BRION("Brión", Provincias.A_CORUNA),
    BUEU("Bueu", Provincias.PONTEVEDRA),
    BURELA("Burela", Provincias.LUGO),
    CABANA_DE_BERGANTINOS("Cabana de Bergantiños", Provincias.A_CORUNA),
    CABANAS("Cabanas", Provincias.A_CORUNA),
    CALDAS_DE_REIS("Caldas de Reis", Provincias.PONTEVEDRA),
    CALVOS_DE_RANDIN("Calvos de Randín", Provincias.OURENSE),
    CAMARINAS("Camariñas", Provincias.A_CORUNA),
    CAMBADOS("Cambados", Provincias.PONTEVEDRA),
    CAMBRE("Cambre", Provincias.A_CORUNA),
    CAMPO_LAMEIRO("Campo Lameiro", Provincias.PONTEVEDRA),
    CANGAS("Cangas", Provincias.PONTEVEDRA),
    A_CANIZA("A Cañiza", Provincias.PONTEVEDRA),
    A_CAPELA("A Capela", Provincias.A_CORUNA),
    CARBALEDA_DE_AVIA("Carballeda de Avia", Provincias.OURENSE),
    CARBALEDA_DE_VALDEORRAS("Carballeda de Valdeorras", Provincias.OURENSE),
    CARBALLEDO("Carballedo", Provincias.LUGO),
    O_CARBALLINO("O Carballiño", Provincias.OURENSE),
    CARBALLO("Carballo", Provincias.A_CORUNA),
    CARINO("Cariño", Provincias.A_CORUNA),
    CENLLE("Cenlle", Provincias.OURENSE),
    CERCEDA("Cerceda", Provincias.A_CORUNA),
    CERDEDO_COTOBADE("Cerdedo-Cotobade", Provincias.PONTEVEDRA),
    CERDIDO("Cerdido", Provincias.A_CORUNA),
    CERVANTES("Cervantes", Provincias.LUGO),
    CERVO("Cervo", Provincias.LUGO),
    CHANDREXA_DE_QUEIXA("Chandrexa de Queixa", Provincias.OURENSE),
    CHANTADA("Chantada", Provincias.LUGO),
    COIROS("Coirós", Provincias.A_CORUNA),
    COLES("Coles", Provincias.OURENSE),
    CORCUBION("Corcubión", Provincias.A_CORUNA),
    O_CORGO("O Corgo", Provincias.LUGO),
    CORISTANCO("Coristanco", Provincias.A_CORUNA),
    CORTEGADA("Cortegada", Provincias.OURENSE),
    A_CORUNA("A Coruña", Provincias.A_CORUNA),
    COSPEITO("Cospeito", Provincias.LUGO),
    COVELO("Covelo", Provincias.PONTEVEDRA),
    CRECENTE("Crecente", Provincias.PONTEVEDRA),
    CUALEDRO("Cualedro", Provincias.OURENSE),
    CULLEREDO("Culleredo", Provincias.A_CORUNA),
    CUNTIS("Cuntis", Provincias.PONTEVEDRA),
    CURTIS("Curtis", Provincias.A_CORUNA),
    DODRO("Dodro", Provincias.A_CORUNA),
    DOZON("Dozón", Provincias.PONTEVEDRA),
    DUMBRIA("Dumbría", Provincias.A_CORUNA),
    ENTRIMO("Entrimo", Provincias.OURENSE),
    ESGOS("Esgos", Provincias.OURENSE),
    A_ESTRADA("A Estrada", Provincias.PONTEVEDRA),
    FENE("Fene", Provincias.A_CORUNA),
    FERROL("Ferrol", Provincias.A_CORUNA),
    FISTERRA("Fisterra", Provincias.A_CORUNA),
    FOLGOSO_DO_COUREL("Folgoso do Courel", Provincias.LUGO),
    A_FONSAGRADA("A Fonsagrada", Provincias.LUGO),
    FORCAEI("Forcarei", Provincias.PONTEVEDRA),
    FORNELOS_DE_MONTES("Fornelos de Montes", Provincias.PONTEVEDRA),
    FOZ("Foz", Provincias.LUGO),
    FRADES("Frades", Provincias.A_CORUNA),
    FRIOL("Friol", Provincias.LUGO),
    GOMESENDE("Gomesende", Provincias.OURENSE),
    GONDOMAR("Gondomar", Provincias.PONTEVEDRA),
    O_GROVE("O Grove", Provincias.PONTEVEDRA),
    A_GUARDA("A Guarda", Provincias.PONTEVEDRA),
    A_GUDINA("A Gudiña", Provincias.OURENSE),
    GUITIRIZ("Guitiriz", Provincias.LUGO),
    GUNTIN("Guntín", Provincias.LUGO),
    A_ILLA_DE_AROUSA("A Illa de Arousa", Provincias.PONTEVEDRA),
    O_INCIO("O Incio", Provincias.LUGO),
    O_IRIXO("O Irixo", Provincias.OURENSE),
    IRIXOA("Irixoa", Provincias.A_CORUNA),
    LALIN("Lalín", Provincias.PONTEVEDRA),
    A_LAMA("A Lama", Provincias.PONTEVEDRA),
    LANCARA("Láncara", Provincias.LUGO),
    A_LARACHA("A Laracha", Provincias.A_CORUNA),
    LAROUCO("Larouco", Provincias.OURENSE),
    LAXE("Laxe", Provincias.A_CORUNA),
    LAZA("Laza", Provincias.OURENSE),
    LEIRO("Leiro", Provincias.OURENSE),
    LOBEIRA("Lobeira", Provincias.OURENSE),
    LOBIOS("Lobios", Provincias.OURENSE),
    LOURENZA("Lourenzá", Provincias.LUGO),
    LOUSAME("Lousame", Provincias.A_CORUNA),
    LUGO("Lugo", Provincias.LUGO),
    MACEDA("Maceda", Provincias.OURENSE),
    MALPICA_DE_BERGANTINOS("Malpica de Bergantiños", Provincias.A_CORUNA),
    MANZANEDA("Manzaneda", Provincias.OURENSE),
    MANON("Mañón", Provincias.A_CORUNA),
    MARIN("Marín", Provincias.PONTEVEDRA),
    MASIDE("Maside", Provincias.OURENSE),
    MAZARICOS("Mazaricos", Provincias.A_CORUNA),
    MEANO("Meaño", Provincias.PONTEVEDRA),
    MEIRA("Meira", Provincias.LUGO),
    MEIS("Meis", Provincias.PONTEVEDRA),
    MELIDE("Melide", Provincias.A_CORUNA),
    MELON("Melón", Provincias.OURENSE),
    A_MERCA("A Merca", Provincias.OURENSE),
    MESIA("Mesía", Provincias.A_CORUNA),
    A_MEZQUITA("A Mezquita", Provincias.OURENSE),
    MINO("Miño", Provincias.A_CORUNA),
    MOANA("Moaña", Provincias.PONTEVEDRA),
    MOECEHE("Moeche", Provincias.A_CORUNA),
    MONDARIZ("Mondariz", Provincias.PONTEVEDRA),
    MONDARIZ_BALNEARIO("Mondariz-Balneario", Provincias.PONTEVEDRA),
    MONDONEDO("Mondoñedo", Provincias.LUGO),
    MONFERO("Monfero", Provincias.A_CORUNA),
    MONFORTE_DE_LEMOS("Monforte de Lemos", Provincias.LUGO),
    MONTEDERRAMO("Montederramo", Provincias.OURENSE),
    MONTERREI("Monterrei", Provincias.OURENSE),
    MONTERROSO("Monterroso", Provincias.LUGO),
    MORAÑA("Moraña", Provincias.PONTEVEDRA),
    MOS("Mos", Provincias.PONTEVEDRA),
    MUGARDOS("Mugardos", Provincias.A_CORUNA),
    MUINOS("Muíños", Provincias.OURENSE),
    MURAS("Muras", Provincias.LUGO),
    MUROS("Muros", Provincias.A_CORUNA),
    A_TEIXEIRA("A Teixeira", Provincias.OURENSE),
    TEO("Teo", Provincias.A_CORUNA),
    TOEN("Toén", Provincias.OURENSE),
    TOMINO("Tomiño", Provincias.PONTEVEDRA),
    TOQUES("Toques", Provincias.A_CORUNA),
    TORDOIA("Tordoia", Provincias.A_CORUNA),
    TOURO("Touro", Provincias.A_CORUNA),
    TRABADA("Trabada", Provincias.LUGO),
    TRASMIRAS("Trasmiras", Provincias.OURENSE),
    TRAZO("Trazo", Provincias.A_CORUNA),
    TRIACASTELA("Triacastela", Provincias.LUGO),
    TUI("Tui", Provincias.PONTEVEDRA),
    VAL_DO_DUBRA("Val do Dubra", Provincias.A_CORUNA),
    O_VALADOURO("O Valadouro", Provincias.LUGO),
    VALDOVINO("Valdoviño", Provincias.A_CORUNA),
    VALGA("Valga", Provincias.PONTEVEDRA),
    VEDRA("Vedra", Provincias.A_CORUNA),
    A_VEIGA("A Veiga", Provincias.OURENSE),
    VEREA("Verea", Provincias.OURENSE),
    VERIN("Verín", Provincias.OURENSE),
    VIANA_DO_BOLO("Viana do Bolo", Provincias.OURENSE),
    O_VICEDO("O Vicedo", Provincias.LUGO),
    VIGO("Vigo", Provincias.PONTEVEDRA),
    VILA_DE_CRUCES("Vila de Cruces", Provincias.PONTEVEDRA),
    VILABOA("Vilaboa", Provincias.PONTEVEDRA),
    VILAGARCIA_DE_AROUSSA("Vilagarcía de Arousa", Provincias.PONTEVEDRA),
    VILALBA("Vilalba", Provincias.LUGO),
    VILAMARIN("Vilamarín", Provincias.OURENSE),
    VILAMARTIN_DE_VALDEORRAS("Vilamartín de Valdeorras", Provincias.OURENSE);

    private final String nombre;
    private final Provincias provincia;

    Municipios(String nombre, Provincias provincia) {
        this.nombre = nombre;
        this.provincia = provincia;
    }

    public String getNombre() {
        return nombre;
    }

    public Provincias getProvincia() {
        return provincia;
    }
}
