package com.hotelgalicia.proyectohotelgalicia.modelos;

public enum Municipios {
    TODOS ("Todos", Provincias.TODAS),
    A_ARNOIA("A Arnoia", Provincias.OURENSE),
    A_BAÑA("A Baña", Provincias.A_CORUNA),
    A_BOLA("A Bola", Provincias.OURENSE),
    A_CAPELA("A Capela", Provincias.A_CORUNA),
    A_CAÑIZA("A Cañiza", Provincias.PONTEVEDRA),
    A_CORUÑA("A Coruña", Provincias.A_CORUNA),
    A_ESTRADA("A Estrada", Provincias.PONTEVEDRA),
    A_FONSAGRADA("A Fonsagrada", Provincias.LUGO),
    A_GUARDA("A Guarda", Provincias.PONTEVEDRA),
    A_GUDIÑA("A Gudiña", Provincias.OURENSE),
    A_ILLA_DE_AROUSA("A Illa De Arousa", Provincias.PONTEVEDRA),
    A_LAMA("A Lama", Provincias.PONTEVEDRA),
    A_LARACHA("A Laracha", Provincias.A_CORUNA),
    A_MERCA("A Merca", Provincias.OURENSE),
    A_MEZQUITA("A Mezquita", Provincias.OURENSE),
    A_PASTORIZA("A Pastoriza", Provincias.LUGO),
    A_PEROXA("A Peroxa", Provincias.OURENSE),
    A_POBRA_DE_TRIVES("A Pobra De Trives", Provincias.OURENSE),
    A_POBRA_DO_BROLLÓN("A Pobra Do Brollón", Provincias.LUGO),
    A_POBRA_DO_CARAMIÑAL("A Pobra Do Caramiñal", Provincias.A_CORUNA),
    A_PONTENOVA("A Pontenova", Provincias.LUGO),
    A_RUA("A Rúa", Provincias.OURENSE),
    A_TEIXEIRA("A Teixeira", Provincias.OURENSE),
    A_VEIGA("A Veiga", Provincias.OURENSE),
    ABADIN("Abadín", Provincias.LUGO),
    ABEGONDO("Abegondo", Provincias.A_CORUNA),
    AGOLADA("Agolada", Provincias.PONTEVEDRA),
    ALFOZ("Alfoz", Provincias.LUGO),
    ALLARIZ("Allariz", Provincias.OURENSE),
    AMES("Ames", Provincias.A_CORUNA),
    AMOEIRO("Amoeiro", Provincias.OURENSE),
    ANTAS_DE_ULLA("Antas De Ulla", Provincias.LUGO),
    ARANGA("Aranga", Provincias.A_CORUNA),
    ARBO("Arbo", Provincias.PONTEVEDRA),
    ARES("Ares", Provincias.A_CORUNA),
    ARTEIXO("Arteixo", Provincias.A_CORUNA),
    ARZUA("Arzúa", Provincias.A_CORUNA),
    AS_NEVES("As Neves", Provincias.PONTEVEDRA),
    AS_NOGAIS("As Nogais", Provincias.LUGO),
    AS_PONTES_DE_GARCÍA_RODRÍGUEZ("As Pontes De García Rodríguez", Provincias.A_CORUNA),
    AS_SOMOZAS("As Somozas", Provincias.A_CORUNA),
    AVIÓN("Avión", Provincias.OURENSE),
    BAIONA("Baiona", Provincias.PONTEVEDRA),
    BALEIRA("Baleira", Provincias.LUGO),
    BALTAR("Baltar", Provincias.OURENSE),
    BANDE("Bande", Provincias.OURENSE),
    BARALLA("Baralla", Provincias.LUGO),
    BARBADÁS("Barbadás", Provincias.OURENSE),
    BARREIROS("Barreiros", Provincias.LUGO),
    BARRO("Barro", Provincias.PONTEVEDRA),
    BAÑOS_DE_MOLGAS("Baños De Molgas", Provincias.OURENSE),
    BEADE("Beade", Provincias.OURENSE),
    BEARIZ("Beariz", Provincias.OURENSE),
    BECERREÁ("Becerreá", Provincias.LUGO),
    BEGONTE("Begonte", Provincias.LUGO),
    BERGONDO("Bergondo", Provincias.A_CORUNA),
    BETANZOS("Betanzos", Provincias.A_CORUNA),
    BOBORÁS("Boborás", Provincias.OURENSE),
    BOIMORTO("Boimorto", Provincias.A_CORUNA),
    BOIRO("Boiro", Provincias.A_CORUNA),
    BOQUEIXÓN("Boqueixón", Provincias.A_CORUNA),
    BRIÓN("Brión", Provincias.A_CORUNA),
    BUEU("Bueu", Provincias.PONTEVEDRA),
    BURELA("Burela", Provincias.LUGO),
    BÓVEDA("Bóveda", Provincias.LUGO),
    CABANA_DE_BERGANTIÑOS("Cabana De Bergantiños", Provincias.A_CORUNA),
    CABANAS("Cabanas", Provincias.A_CORUNA),
    CALDAS_DE_REIS("Caldas De Reis", Provincias.PONTEVEDRA),
    CALVOS_DE_RANDÍN("Calvos De Randín", Provincias.OURENSE),
    CAMARIÑAS("Camariñas", Provincias.A_CORUNA),
    CAMBADOS("Cambados", Provincias.PONTEVEDRA),
    CAMBRE("Cambre", Provincias.A_CORUNA),
    CAMPO_LAMEIRO("Campo Lameiro", Provincias.PONTEVEDRA),
    CANGAS("Cangas", Provincias.PONTEVEDRA),
    CARBALLEDA_DE_AVIA("Carballeda De Avia", Provincias.OURENSE),
    CARBALLEDA_DE_VALDEORRAS("Carballeda De Valdeorras", Provincias.OURENSE),
    CARBALLEDO("Carballedo", Provincias.LUGO),
    CARIÑO("Cariño", Provincias.A_CORUNA),
    CARNOTA("Carnota", Provincias.A_CORUNA),
    CARRAL("Carral", Provincias.A_CORUNA),
    CARTELLE("Cartelle", Provincias.OURENSE),
    CASTRELO_DE_MIÑO("Castrelo De Miño", Provincias.OURENSE),
    CASTRELO_DO_VAL("Castrelo Do Val", Provincias.OURENSE),
    CASTRO_CALDELAS("Castro Caldelas", Provincias.OURENSE),
    CASTRO_DE_REI("Castro De Rei", Provincias.LUGO),
    CASTROVERDE("Castroverde", Provincias.LUGO),
    CATOIRA("Catoira", Provincias.PONTEVEDRA),
    CEDEIRA("Cedeira", Provincias.A_CORUNA),
    CEE("Cee (A Coruña)", Provincias.A_CORUNA),
    CELANOVA("Celanova", Provincias.OURENSE),
    CENLLE("Cenlle", Provincias.OURENSE),
    CERDEDO("Cerdedo", Provincias.PONTEVEDRA),
    CERDEDO_COTOBADE("Cerdedo-Cotobade", Provincias.PONTEVEDRA),
    CERDIDO("Cerdido", Provincias.A_CORUNA),
    CERVANTES("Cervantes (Lugo)", Provincias.LUGO),
    CERVO("Cervo", Provincias.LUGO),
    CHANDREXA_DE_QUEIXA("Chandrexa De Queixa", Provincias.OURENSE),
    CHANTADA("Chantada", Provincias.LUGO),
    COIRÓS("Coirós", Provincias.A_CORUNA),
    COLES("Coles", Provincias.OURENSE),
    CORCUBIÓN("Corcubión", Provincias.A_CORUNA),
    CORISTANCO("Coristanco", Provincias.A_CORUNA),
    CORTEGADA("Cortegada", Provincias.OURENSE),
    COSPEITO("Cospeito", Provincias.LUGO),
    COTOBADE("Cotobade", Provincias.PONTEVEDRA),
    COVELO("Covelo", Provincias.PONTEVEDRA),
    CRECENTE("Crecente", Provincias.PONTEVEDRA),
    CUALEDRO("Cualedro", Provincias.OURENSE),
    CULLEREDO("Culleredo", Provincias.A_CORUNA),
    CUNTIS("Cuntis", Provincias.PONTEVEDRA),
    CURTIS("Curtis", Provincias.A_CORUNA),
    DODRO("Dodro", Provincias.A_CORUNA),
    DOZÓN("Dozón", Provincias.PONTEVEDRA),
    DUMBRÍA("Dumbría", Provincias.A_CORUNA),
    ENTRIMO("Entrimo", Provincias.OURENSE),
    ESGOS("Esgos", Provincias.OURENSE),
    FENE("Fene", Provincias.A_CORUNA),
    FERROL("Ferrol", Provincias.A_CORUNA),
    FISTERRA("Fisterra", Provincias.A_CORUNA),
    FOLGOSO_DO_COUREL("Folgoso Do Courel", Provincias.LUGO),
    FORCAREI("Forcarei", Provincias.PONTEVEDRA),
    FORNELOS_DE_MONTES("Fornelos De Montes", Provincias.PONTEVEDRA),
    FOZ("Foz", Provincias.LUGO),
    FRADES("Frades", Provincias.A_CORUNA),
    FRIOL("Friol", Provincias.LUGO),
    GOMESENDE("Gomesende", Provincias.OURENSE),
    GONDOMAR("Gondomar", Provincias.PONTEVEDRA),
    GUITIRIZ("Guitiriz", Provincias.LUGO),
    GUNTÍN("Guntín", Provincias.LUGO),
    IRIXOA("Irixoa", Provincias.A_CORUNA),
    LALÍN("Lalín", Provincias.PONTEVEDRA),
    LAROUCO("Larouco", Provincias.OURENSE),
    LAXE("Laxe", Provincias.A_CORUNA),
    LAZA("Laza", Provincias.OURENSE),
    LEIRO("Leiro", Provincias.OURENSE),
    LOBERA("Lobera", Provincias.OURENSE),
    LOBIOS("Lobios", Provincias.OURENSE),
    LOURENZÁ("Lourenzá", Provincias.LUGO),
    LOUSAME("Lousame", Provincias.A_CORUNA),
    LUGO("Lugo", Provincias.LUGO),
    LÁNCARA("Láncara", Provincias.LUGO),
    MACEDA("Maceda", Provincias.OURENSE),
    MALPICA_DE_BERGANTIÑOS("Malpica De Bergantiños", Provincias.A_CORUNA),
    MANZANEDA("Manzaneda", Provincias.OURENSE),
    MARÍN("Marín", Provincias.PONTEVEDRA),
    MASIDE("Maside", Provincias.OURENSE),
    MAZARICOS("Mazaricos", Provincias.A_CORUNA),
    MAÑÓN("Mañón", Provincias.A_CORUNA),
    MEAÑO("Meaño", Provincias.PONTEVEDRA),
    MEIRA("Meira", Provincias.LUGO),
    MEIS("Meis", Provincias.PONTEVEDRA),
    MELLID("Mellid", Provincias.A_CORUNA),
    MELÓN("Melón", Provincias.OURENSE),
    MESÍA("Mesía", Provincias.A_CORUNA),
    MIÑO("Miño", Provincias.A_CORUNA),
    MOAÑA("Moaña", Provincias.PONTEVEDRA),
    MOECHE("Moeche", Provincias.A_CORUNA),
    MONDARIZ("Mondariz", Provincias.PONTEVEDRA),
    MONDARIZ_BALNEARIO("Mondariz-Balneario", Provincias.PONTEVEDRA),
    MONDOÑEDO("Mondoñedo", Provincias.LUGO),
    MONFERO("Monfero", Provincias.A_CORUNA),
    MONFORTE_DE_LEMOS("Monforte De Lemos", Provincias.LUGO),
    MONTEDERRAMO("Montederramo", Provincias.OURENSE),
    MONTERREI("Monterrei", Provincias.OURENSE),
    MONTERROSO("Monterroso", Provincias.LUGO),
    MORAÑA("Moraña", Provincias.PONTEVEDRA),
    MOS("Mos", Provincias.PONTEVEDRA),
    MUGARDOS("Mugardos", Provincias.A_CORUNA),
    MURAS("Muras", Provincias.LUGO),
    MUROS("Muros (A Coruña)", Provincias.A_CORUNA),
    MUXÍA("Muxía", Provincias.A_CORUNA),
    MUÍÑOS("Muíños", Provincias.OURENSE),
    NARÓN("Narón", Provincias.A_CORUNA),
    NAVIA_DE_SUARNA("Navia De Suarna", Provincias.LUGO),
    NEDA("Neda", Provincias.A_CORUNA),
    NEGREIRA("Negreira", Provincias.A_CORUNA),
    NEGUEIRA_DE_MUÑIZ("Negueira De Muñiz", Provincias.LUGO),
    NIGRÁN("Nigrán", Provincias.PONTEVEDRA),
    NOGUEIRA_DE_RAMUÍN("Nogueira De Ramuín", Provincias.OURENSE),
    NOIA("Noia", Provincias.A_CORUNA),
    O_BARCO_DE_VALDEORRAS("O Barco De Valdeorras", Provincias.OURENSE),
    O_BOLO("O Bolo", Provincias.OURENSE),
    O_CARBALLIÑO("O Carballiño", Provincias.OURENSE),
    O_CORGO("O Corgo", Provincias.LUGO),
    O_GROVE("O Grove", Provincias.PONTEVEDRA),
    O_INCIO("O Incio", Provincias.LUGO),
    O_IRIXO("O Irixo", Provincias.OURENSE),
    O_PEREIRO_DE_AGUIAR("O Pereiro De Aguiar", Provincias.OURENSE),
    O_PINO("O Pino", Provincias.A_CORUNA),
    O_PORRIÑO("O Porriño", Provincias.PONTEVEDRA),
    O_PÁRAMO("O Páramo", Provincias.LUGO),
    O_ROSAL("O Rosal", Provincias.PONTEVEDRA),
    O_SAVIÑAO("O Saviñao", Provincias.LUGO),
    O_VALADOURO("O Valadouro", Provincias.LUGO),
    O_VICEDO("O Vicedo", Provincias.LUGO),
    OIA("Oia", Provincias.PONTEVEDRA),
    OLEIROS("Oleiros", Provincias.A_CORUNA),
    ORDES("Ordes", Provincias.A_CORUNA),
    OROSO("Oroso", Provincias.A_CORUNA),
    ORTIGUEIRA("Ortigueira", Provincias.A_CORUNA),
    OS_BLANCOS("Os Blancos", Provincias.OURENSE),
    OURENSE("Ourense", Provincias.OURENSE),
    OUROL("Ourol", Provincias.LUGO),
    OUTEIRO_DE_REI("Outeiro De Rei", Provincias.LUGO),
    OUTES("Outes", Provincias.A_CORUNA),
    OZA_CESURAS("Oza-Cesuras", Provincias.A_CORUNA),
    OÍMBRA("Oímbra", Provincias.OURENSE),
    PADERNE("Paderne", Provincias.A_CORUNA),
    PADERNE_DE_ALLARIZ("Paderne De Allariz", Provincias.OURENSE),
    PADRENDA("Padrenda", Provincias.OURENSE),
    PADRÓN("Padrón", Provincias.A_CORUNA),
    PALAS_DE_REI("Palas De Rei", Provincias.LUGO),
    PANTÓN("Pantón", Provincias.LUGO),
    PARADA_DE_SIL("Parada De Sil", Provincias.OURENSE),
    PARADELA("Paradela", Provincias.LUGO),
    PAZOS_DE_BORBÉN("Pazos De Borbén", Provincias.PONTEVEDRA),
    PEDRAFITA_DO_CEBREIRO("Pedrafita Do Cebreiro", Provincias.LUGO),
    PETÍN("Petín", Provincias.OURENSE),
    PIÑOR("Piñor", Provincias.OURENSE),
    POIO("Poio", Provincias.PONTEVEDRA),
    POL("Pol", Provincias.LUGO),
    PONTE_CALDELAS("Ponte Caldelas", Provincias.PONTEVEDRA),
    PONTEAREAS("Ponteareas", Provincias.PONTEVEDRA),
    PONTECESO("Ponteceso", Provincias.A_CORUNA),
    PONTECESURES("Pontecesures", Provincias.PONTEVEDRA),
    PONTEDEUME("Pontedeume", Provincias.A_CORUNA),
    PONTEDEVA("Pontedeva", Provincias.OURENSE),
    PONTEVEDRA("Pontevedra", Provincias.PONTEVEDRA),
    PORQUERA("Porquera", Provincias.OURENSE),
    PORTAS("Portas", Provincias.PONTEVEDRA),
    PORTO_DO_SON("Porto Do Son", Provincias.A_CORUNA),
    PORTOMARÍN("Portomarín", Provincias.LUGO),
    PUNXÍN("Punxín", Provincias.OURENSE),
    QUINTELA_DE_LEIRADO("Quintela De Leirado", Provincias.OURENSE),
    QUIROGA("Quiroga", Provincias.LUGO),
    RAIRIZ_DE_VEIGA("Rairiz De Veiga", Provincias.OURENSE),
    RAMIRÁS("Ramirás", Provincias.OURENSE),
    REDONDELA("Redondela", Provincias.PONTEVEDRA),
    RIANXO("Rianxo", Provincias.A_CORUNA),
    RIBADAVIA("Ribadavia", Provincias.OURENSE),
    RIBADEO("Ribadeo", Provincias.LUGO),
    RIBADUMIA("Ribadumia", Provincias.PONTEVEDRA),
    RIBAS_DE_SIL("Ribas De Sil", Provincias.LUGO),
    RIBEIRA("Ribeira", Provincias.A_CORUNA),
    RIBEIRA_DE_PIQUÍN("Ribeira De Piquín", Provincias.LUGO),
    RIOTORTO("Riotorto", Provincias.LUGO),
    RIÓS("Riós", Provincias.OURENSE),
    RODEIRO("Rodeiro", Provincias.PONTEVEDRA),
    ROIS("Rois", Provincias.A_CORUNA),
    RUBIÁ("Rubiá", Provincias.OURENSE),
    RÁBADE("Rábade", Provincias.LUGO),
    SADA("Sada", Provincias.A_CORUNA),
    SALCEDA_DE_CASELAS("Salceda De Caselas", Provincias.PONTEVEDRA),
    SALVATERRA_DE_MIÑO("Salvaterra De Miño", Provincias.PONTEVEDRA),
    SAMOS("Samos", Provincias.LUGO),
    SAN_AMARO("San Amaro", Provincias.OURENSE),
    SAN_CIBRAO_DAS_VIÑAS("San Cibrao Das Viñas", Provincias.OURENSE),
    SAN_CRISTOVO_DE_CEA("San Cristovo De Cea", Provincias.OURENSE),
    SAN_SADURNIÑO("San Sadurniño", Provincias.A_CORUNA),
    SAN_XOÁN_DE_RÍO("San Xoán De Río", Provincias.OURENSE),
    SANDIÁS("Sandiás", Provincias.OURENSE),
    SANTA_COMBA("Santa Comba", Provincias.A_CORUNA),
    SANTIAGO_DE_COMPOSTELA("Santiago De Compostela", Provincias.A_CORUNA),
    SANTISO("Santiso", Provincias.A_CORUNA),
    SANXENXO("Sanxenxo", Provincias.PONTEVEDRA),
    SARREAUS("Sarreaus", Provincias.OURENSE),
    SARRIA("Sarria (Lugo)", Provincias.LUGO),
    SILLEDA("Silleda", Provincias.PONTEVEDRA),
    SOBER("Sober", Provincias.LUGO),
    SOBRADO("Sobrado (A Coruña)", Provincias.A_CORUNA),
    SOUTOMAIOR("Soutomaior", Provincias.PONTEVEDRA),
    TABOADA("Taboada", Provincias.LUGO),
    TABOADELA("Taboadela", Provincias.OURENSE),
    TEO("Teo", Provincias.A_CORUNA),
    TOMIÑO("Tomiño", Provincias.PONTEVEDRA),
    TOQUES("Toques", Provincias.A_CORUNA),
    TORDOIA("Tordoia", Provincias.A_CORUNA),
    TOURO("Touro", Provincias.A_CORUNA),
    TOÉN("Toén", Provincias.OURENSE),
    TRABADA("Trabada", Provincias.LUGO),
    TRASMIRAS("Trasmiras", Provincias.OURENSE),
    TRAZO("Trazo", Provincias.A_CORUNA),
    TRIACASTELA("Triacastela", Provincias.LUGO),
    TUI("Tui", Provincias.PONTEVEDRA),
    VAL_DO_DUBRA("Val Do Dubra", Provincias.A_CORUNA),
    VALDOVIÑO("Valdoviño", Provincias.A_CORUNA),
    VALGA("Valga", Provincias.PONTEVEDRA),
    VEDRA("Vedra", Provincias.A_CORUNA),
    VEREA("Verea", Provincias.OURENSE),
    VERÍN("Verín", Provincias.OURENSE),
    VIANA_DO_BOLO("Viana Do Bolo", Provincias.OURENSE),
    VIGO("Vigo", Provincias.PONTEVEDRA),
    VILA_DE_CRUCES("Vila De Cruces", Provincias.PONTEVEDRA),
    VILABOA("Vilaboa", Provincias.PONTEVEDRA),
    VILAGARCÍA_DE_AROUSA("Vilagarcía De Arousa", Provincias.PONTEVEDRA),
    VILALBA("Vilalba", Provincias.LUGO),
    VILAMARTÍN_DE_VALDEORRAS("Vilamartín De Valdeorras", Provincias.OURENSE),
    VILAMARÍN("Vilamarín", Provincias.OURENSE),
    VILANOVA_DE_AROUSA("Vilanova De Arousa", Provincias.PONTEVEDRA),
    VILAR_DE_BARRIO("Vilar De Barrio", Provincias.OURENSE),
    VILAR_DE_SANTOS("Vilar De Santos", Provincias.OURENSE),
    VILARDEVÓS("Vilardevós", Provincias.OURENSE),
    VILARIÑO_DE_CONSO("Vilariño De Conso", Provincias.OURENSE),
    VILARMAIOR("Vilarmaior", Provincias.A_CORUNA),
    VILASANTAR("Vilasantar", Provincias.A_CORUNA),
    VIMIANZO("Vimianzo", Provincias.A_CORUNA),
    VIVEIRO("Viveiro", Provincias.LUGO),
    XERMADE("Xermade", Provincias.LUGO),
    XINZO_DE_LIMIA("Xinzo De Limia", Provincias.OURENSE),
    XOVE("Xove", Provincias.LUGO),
    XUNQUEIRA_DE_AMBÍA("Xunqueira De Ambía", Provincias.OURENSE),
    XUNQUEIRA_DE_ESPADANEDO("Xunqueira De Espadanedo", Provincias.OURENSE),
    ZAS("Zas", Provincias.A_CORUNA);

    private final String nombre;
    private final Provincias provincia;

    Municipios(String nombre, Provincias provincia) {
        this.nombre = nombre;
        this.provincia = provincia;
    }

    public String getNombre() {
        return nombre;
    }

    public Provincias getProvincia() {
        return provincia;
    }
}
